// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.6
// source: api/cconfig.proto

//this is the proto package name,all proto in this project must use this name as the proto package name

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Cinforeq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groupname string `protobuf:"bytes,1,opt,name=groupname,proto3" json:"groupname,omitempty"` //empty:false
	Appname   string `protobuf:"bytes,2,opt,name=appname,proto3" json:"appname,omitempty"`     //empty:false
}

func (x *Cinforeq) Reset() {
	*x = Cinforeq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_cconfig_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cinforeq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cinforeq) ProtoMessage() {}

func (x *Cinforeq) ProtoReflect() protoreflect.Message {
	mi := &file_api_cconfig_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cinforeq.ProtoReflect.Descriptor instead.
func (*Cinforeq) Descriptor() ([]byte, []int) {
	return file_api_cconfig_proto_rawDescGZIP(), []int{0}
}

func (x *Cinforeq) GetGroupname() string {
	if x != nil {
		return x.Groupname
	}
	return ""
}

func (x *Cinforeq) GetAppname() string {
	if x != nil {
		return x.Appname
	}
	return ""
}

type Cinforesp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurId     string `protobuf:"bytes,1,opt,name=cur_id,json=curId,proto3" json:"cur_id,omitempty"`
	CurConfig string `protobuf:"bytes,2,opt,name=cur_config,json=curConfig,proto3" json:"cur_config,omitempty"`
	//ids are sortted by create time
	AllIds []string `protobuf:"bytes,3,rep,name=all_ids,json=allIds,proto3" json:"all_ids,omitempty"`
}

func (x *Cinforesp) Reset() {
	*x = Cinforesp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_cconfig_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cinforesp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cinforesp) ProtoMessage() {}

func (x *Cinforesp) ProtoReflect() protoreflect.Message {
	mi := &file_api_cconfig_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cinforesp.ProtoReflect.Descriptor instead.
func (*Cinforesp) Descriptor() ([]byte, []int) {
	return file_api_cconfig_proto_rawDescGZIP(), []int{1}
}

func (x *Cinforesp) GetCurId() string {
	if x != nil {
		return x.CurId
	}
	return ""
}

func (x *Cinforesp) GetCurConfig() string {
	if x != nil {
		return x.CurConfig
	}
	return ""
}

func (x *Cinforesp) GetAllIds() []string {
	if x != nil {
		return x.AllIds
	}
	return nil
}

type Csetreq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groupname string `protobuf:"bytes,1,opt,name=groupname,proto3" json:"groupname,omitempty"` //empty:false
	Appname   string `protobuf:"bytes,2,opt,name=appname,proto3" json:"appname,omitempty"`     //empty:false
	Config    string `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *Csetreq) Reset() {
	*x = Csetreq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_cconfig_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Csetreq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Csetreq) ProtoMessage() {}

func (x *Csetreq) ProtoReflect() protoreflect.Message {
	mi := &file_api_cconfig_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Csetreq.ProtoReflect.Descriptor instead.
func (*Csetreq) Descriptor() ([]byte, []int) {
	return file_api_cconfig_proto_rawDescGZIP(), []int{2}
}

func (x *Csetreq) GetGroupname() string {
	if x != nil {
		return x.Groupname
	}
	return ""
}

func (x *Csetreq) GetAppname() string {
	if x != nil {
		return x.Appname
	}
	return ""
}

func (x *Csetreq) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type Csetresp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Csetresp) Reset() {
	*x = Csetresp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_cconfig_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Csetresp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Csetresp) ProtoMessage() {}

func (x *Csetresp) ProtoReflect() protoreflect.Message {
	mi := &file_api_cconfig_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Csetresp.ProtoReflect.Descriptor instead.
func (*Csetresp) Descriptor() ([]byte, []int) {
	return file_api_cconfig_proto_rawDescGZIP(), []int{3}
}

type Cgetreq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groupname string `protobuf:"bytes,1,opt,name=groupname,proto3" json:"groupname,omitempty"` //empty:false
	Appname   string `protobuf:"bytes,2,opt,name=appname,proto3" json:"appname,omitempty"`     //empty:false
	Id        string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`               //empty:false
}

func (x *Cgetreq) Reset() {
	*x = Cgetreq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_cconfig_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cgetreq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cgetreq) ProtoMessage() {}

func (x *Cgetreq) ProtoReflect() protoreflect.Message {
	mi := &file_api_cconfig_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cgetreq.ProtoReflect.Descriptor instead.
func (*Cgetreq) Descriptor() ([]byte, []int) {
	return file_api_cconfig_proto_rawDescGZIP(), []int{4}
}

func (x *Cgetreq) GetGroupname() string {
	if x != nil {
		return x.Groupname
	}
	return ""
}

func (x *Cgetreq) GetAppname() string {
	if x != nil {
		return x.Appname
	}
	return ""
}

func (x *Cgetreq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Cgetresp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Config string `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *Cgetresp) Reset() {
	*x = Cgetresp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_cconfig_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cgetresp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cgetresp) ProtoMessage() {}

func (x *Cgetresp) ProtoReflect() protoreflect.Message {
	mi := &file_api_cconfig_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cgetresp.ProtoReflect.Descriptor instead.
func (*Cgetresp) Descriptor() ([]byte, []int) {
	return file_api_cconfig_proto_rawDescGZIP(), []int{5}
}

func (x *Cgetresp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cgetresp) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type Cgroupsreq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Cgroupsreq) Reset() {
	*x = Cgroupsreq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_cconfig_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cgroupsreq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cgroupsreq) ProtoMessage() {}

func (x *Cgroupsreq) ProtoReflect() protoreflect.Message {
	mi := &file_api_cconfig_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cgroupsreq.ProtoReflect.Descriptor instead.
func (*Cgroupsreq) Descriptor() ([]byte, []int) {
	return file_api_cconfig_proto_rawDescGZIP(), []int{6}
}

type Cgroupsresp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groups []string `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *Cgroupsresp) Reset() {
	*x = Cgroupsresp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_cconfig_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cgroupsresp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cgroupsresp) ProtoMessage() {}

func (x *Cgroupsresp) ProtoReflect() protoreflect.Message {
	mi := &file_api_cconfig_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cgroupsresp.ProtoReflect.Descriptor instead.
func (*Cgroupsresp) Descriptor() ([]byte, []int) {
	return file_api_cconfig_proto_rawDescGZIP(), []int{7}
}

func (x *Cgroupsresp) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

type Cappsreq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groupname string `protobuf:"bytes,1,opt,name=groupname,proto3" json:"groupname,omitempty"` //empty:false
}

func (x *Cappsreq) Reset() {
	*x = Cappsreq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_cconfig_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cappsreq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cappsreq) ProtoMessage() {}

func (x *Cappsreq) ProtoReflect() protoreflect.Message {
	mi := &file_api_cconfig_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cappsreq.ProtoReflect.Descriptor instead.
func (*Cappsreq) Descriptor() ([]byte, []int) {
	return file_api_cconfig_proto_rawDescGZIP(), []int{8}
}

func (x *Cappsreq) GetGroupname() string {
	if x != nil {
		return x.Groupname
	}
	return ""
}

type Cappsresp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Apps []string `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
}

func (x *Cappsresp) Reset() {
	*x = Cappsresp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_cconfig_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cappsresp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cappsresp) ProtoMessage() {}

func (x *Cappsresp) ProtoReflect() protoreflect.Message {
	mi := &file_api_cconfig_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cappsresp.ProtoReflect.Descriptor instead.
func (*Cappsresp) Descriptor() ([]byte, []int) {
	return file_api_cconfig_proto_rawDescGZIP(), []int{9}
}

func (x *Cappsresp) GetApps() []string {
	if x != nil {
		return x.Apps
	}
	return nil
}

var File_api_cconfig_proto protoreflect.FileDescriptor

var file_api_cconfig_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x42, 0x0a, 0x08, 0x63,
	0x69, 0x6e, 0x66, 0x6f, 0x72, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x5a, 0x0a, 0x09, 0x63, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x65, 0x73, 0x70, 0x12, 0x15, 0x0a, 0x06,
	0x63, 0x75, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x75,
	0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x75, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x75, 0x72, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x73, 0x22, 0x59, 0x0a, 0x07, 0x63,
	0x73, 0x65, 0x74, 0x72, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x0a, 0x0a, 0x08, 0x63, 0x73, 0x65, 0x74, 0x72, 0x65,
	0x73, 0x70, 0x22, 0x51, 0x0a, 0x07, 0x63, 0x67, 0x65, 0x74, 0x72, 0x65, 0x71, 0x12, 0x1c, 0x0a,
	0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x70, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70,
	0x70, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x32, 0x0a, 0x08, 0x63, 0x67, 0x65, 0x74, 0x72, 0x65, 0x73,
	0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x0c, 0x0a, 0x0a, 0x63, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x72, 0x65, 0x71, 0x22, 0x25, 0x0a, 0x0b, 0x63, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x72, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0x28,
	0x0a, 0x08, 0x63, 0x61, 0x70, 0x70, 0x73, 0x72, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1f, 0x0a, 0x09, 0x63, 0x61, 0x70, 0x70,
	0x73, 0x72, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x70, 0x70, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x70, 0x70, 0x73, 0x32, 0xef, 0x01, 0x0a, 0x07, 0x63, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2c, 0x0a, 0x05, 0x63, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x10,
	0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x63, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x65, 0x71,
	0x1a, 0x11, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x63, 0x69, 0x6e, 0x66, 0x6f, 0x72,
	0x65, 0x73, 0x70, 0x12, 0x29, 0x0a, 0x04, 0x63, 0x73, 0x65, 0x74, 0x12, 0x0f, 0x2e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x63, 0x73, 0x65, 0x74, 0x72, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x63, 0x73, 0x65, 0x74, 0x72, 0x65, 0x73, 0x70, 0x12, 0x29,
	0x0a, 0x04, 0x63, 0x67, 0x65, 0x74, 0x12, 0x0f, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x63, 0x67, 0x65, 0x74, 0x72, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x63, 0x67, 0x65, 0x74, 0x72, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x07, 0x63, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x12, 0x12, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x63, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x72, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x63, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x72, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a,
	0x05, 0x63, 0x61, 0x70, 0x70, 0x73, 0x12, 0x10, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x63, 0x61, 0x70, 0x70, 0x73, 0x72, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x63, 0x61, 0x70, 0x70, 0x73, 0x72, 0x65, 0x73, 0x70, 0x42, 0x10, 0x5a, 0x0e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_cconfig_proto_rawDescOnce sync.Once
	file_api_cconfig_proto_rawDescData = file_api_cconfig_proto_rawDesc
)

func file_api_cconfig_proto_rawDescGZIP() []byte {
	file_api_cconfig_proto_rawDescOnce.Do(func() {
		file_api_cconfig_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_cconfig_proto_rawDescData)
	})
	return file_api_cconfig_proto_rawDescData
}

var file_api_cconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_cconfig_proto_goTypes = []interface{}{
	(*Cinforeq)(nil),    // 0: config.cinforeq
	(*Cinforesp)(nil),   // 1: config.cinforesp
	(*Csetreq)(nil),     // 2: config.csetreq
	(*Csetresp)(nil),    // 3: config.csetresp
	(*Cgetreq)(nil),     // 4: config.cgetreq
	(*Cgetresp)(nil),    // 5: config.cgetresp
	(*Cgroupsreq)(nil),  // 6: config.cgroupsreq
	(*Cgroupsresp)(nil), // 7: config.cgroupsresp
	(*Cappsreq)(nil),    // 8: config.cappsreq
	(*Cappsresp)(nil),   // 9: config.cappsresp
}
var file_api_cconfig_proto_depIdxs = []int32{
	0, // 0: config.cconfig.cinfo:input_type -> config.cinforeq
	2, // 1: config.cconfig.cset:input_type -> config.csetreq
	4, // 2: config.cconfig.cget:input_type -> config.cgetreq
	6, // 3: config.cconfig.cgroups:input_type -> config.cgroupsreq
	8, // 4: config.cconfig.capps:input_type -> config.cappsreq
	1, // 5: config.cconfig.cinfo:output_type -> config.cinforesp
	3, // 6: config.cconfig.cset:output_type -> config.csetresp
	5, // 7: config.cconfig.cget:output_type -> config.cgetresp
	7, // 8: config.cconfig.cgroups:output_type -> config.cgroupsresp
	9, // 9: config.cconfig.capps:output_type -> config.cappsresp
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_cconfig_proto_init() }
func file_api_cconfig_proto_init() {
	if File_api_cconfig_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_cconfig_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cinforeq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_cconfig_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cinforesp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_cconfig_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Csetreq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_cconfig_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Csetresp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_cconfig_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cgetreq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_cconfig_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cgetresp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_cconfig_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cgroupsreq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_cconfig_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cgroupsresp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_cconfig_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cappsreq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_cconfig_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cappsresp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_cconfig_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_cconfig_proto_goTypes,
		DependencyIndexes: file_api_cconfig_proto_depIdxs,
		MessageInfos:      file_api_cconfig_proto_msgTypes,
	}.Build()
	File_api_cconfig_proto = out.File
	file_api_cconfig_proto_rawDesc = nil
	file_api_cconfig_proto_goTypes = nil
	file_api_cconfig_proto_depIdxs = nil
}
