// Code generated by protoc-gen-go-rpc. DO NOT EDIT.

package api

import (
	context "context"
	rpc "github.com/chenjie199234/Corelib/rpc"
	error1 "github.com/chenjie199234/Corelib/util/error"
	metadata "github.com/chenjie199234/Corelib/util/metadata"
	proto "github.com/golang/protobuf/proto"
	time "time"
)

var RpcPathCconfigCinfo = "/config.Cconfig/Cinfo"
var RpcPathCconfigCset = "/config.Cconfig/Cset"
var RpcPathCconfigCrollback = "/config.Cconfig/Crollback"
var RpcPathCconfigCget = "/config.Cconfig/Cget"
var RpcPathCconfigCgroups = "/config.Cconfig/Cgroups"
var RpcPathCconfigCapps = "/config.Cconfig/Capps"

// CconfigRpcClient is the client API for Cconfig service.
type CconfigRpcClient interface {
	//one specific app's current info
	Cinfo(context.Context, *Cinforeq) (*Cinforesp, error)
	//set one specific app's config
	Cset(context.Context, *Csetreq) (*Csetresp, error)
	//rollback one specific app's config
	Crollback(context.Context, *Crollbackreq) (*Crollbackresp, error)
	//get one specific app's config
	Cget(context.Context, *Cgetreq) (*Cgetresp, error)
	//get all groups
	Cgroups(context.Context, *Cgroupsreq) (*Cgroupsresp, error)
	//get all apps
	Capps(context.Context, *Cappsreq) (*Cappsresp, error)
}

type cconfigRpcClient struct {
	cc *rpc.RpcClient
}

//has race,will only return the first's call's client,the config will use the first call's config
func NewCconfigRpcClient(timeout, conntimeout, hearttimeout, heartprobe time.Duration, selfgroup, selfname string, verifydata string, picker rpc.PickHandler, discover rpc.DiscoveryHandler) (CconfigRpcClient, error) {
	c := &rpc.Config{
		Timeout:                time.Duration(timeout),
		ConnTimeout:            time.Duration(conntimeout),
		HeartTimeout:           time.Duration(hearttimeout),
		HeartPorbe:             time.Duration(heartprobe),
		GroupNum:               1,
		SocketRBuf:             1024,
		SocketWBuf:             1024,
		MaxMsgLen:              65535,
		MaxBufferedWriteMsgNum: 1024,
	}
	cc, e := rpc.NewRpcClient(c, selfgroup, selfname, verifydata, Group, Name, picker, discover)
	if e != nil {
		return nil, e
	}
	return &cconfigRpcClient{cc: cc}, nil
}

func (c *cconfigRpcClient) Cinfo(ctx context.Context, req *Cinforeq) (*Cinforesp, error) {
	if req == nil {
		return nil, rpc.ERRREQUEST
	}
	//empty check
	if len(req.Groupname) == 0 {
		return nil, rpc.ERRREQUEST
	}
	//empty check
	if len(req.Appname) == 0 {
		return nil, rpc.ERRREQUEST
	}
	//gte check
	if float64(req.OpNum) < 0 {
		return nil, rpc.ERRREQUEST
	}
	reqd, _ := proto.Marshal(req)
	callback, e := c.cc.Call(ctx, 500000000, RpcPathCconfigCinfo, reqd, metadata.GetAllMetadata(ctx))
	if e.(*error1.Error) != nil {
		return nil, e
	}
	resp := new(Cinforesp)
	if e := proto.Unmarshal(callback, resp); e != nil {
		return nil, rpc.ERRRESPONSE
	}
	return resp, nil
}
func (c *cconfigRpcClient) Cset(ctx context.Context, req *Csetreq) (*Csetresp, error) {
	if req == nil {
		return nil, rpc.ERRREQUEST
	}
	//empty check
	if len(req.Groupname) == 0 {
		return nil, rpc.ERRREQUEST
	}
	//empty check
	if len(req.Appname) == 0 {
		return nil, rpc.ERRREQUEST
	}
	reqd, _ := proto.Marshal(req)
	callback, e := c.cc.Call(ctx, 500000000, RpcPathCconfigCset, reqd, metadata.GetAllMetadata(ctx))
	if e.(*error1.Error) != nil {
		return nil, e
	}
	resp := new(Csetresp)
	if e := proto.Unmarshal(callback, resp); e != nil {
		return nil, rpc.ERRRESPONSE
	}
	return resp, nil
}
func (c *cconfigRpcClient) Crollback(ctx context.Context, req *Crollbackreq) (*Crollbackresp, error) {
	if req == nil {
		return nil, rpc.ERRREQUEST
	}
	//empty check
	if len(req.Groupname) == 0 {
		return nil, rpc.ERRREQUEST
	}
	//empty check
	if len(req.Appname) == 0 {
		return nil, rpc.ERRREQUEST
	}
	//empty check
	if len(req.Id) == 0 {
		return nil, rpc.ERRREQUEST
	}
	reqd, _ := proto.Marshal(req)
	callback, e := c.cc.Call(ctx, 500000000, RpcPathCconfigCrollback, reqd, metadata.GetAllMetadata(ctx))
	if e.(*error1.Error) != nil {
		return nil, e
	}
	resp := new(Crollbackresp)
	if e := proto.Unmarshal(callback, resp); e != nil {
		return nil, rpc.ERRRESPONSE
	}
	return resp, nil
}
func (c *cconfigRpcClient) Cget(ctx context.Context, req *Cgetreq) (*Cgetresp, error) {
	if req == nil {
		return nil, rpc.ERRREQUEST
	}
	//empty check
	if len(req.Groupname) == 0 {
		return nil, rpc.ERRREQUEST
	}
	//empty check
	if len(req.Appname) == 0 {
		return nil, rpc.ERRREQUEST
	}
	//empty check
	if len(req.Id) == 0 {
		return nil, rpc.ERRREQUEST
	}
	reqd, _ := proto.Marshal(req)
	callback, e := c.cc.Call(ctx, 500000000, RpcPathCconfigCget, reqd, metadata.GetAllMetadata(ctx))
	if e.(*error1.Error) != nil {
		return nil, e
	}
	resp := new(Cgetresp)
	if e := proto.Unmarshal(callback, resp); e != nil {
		return nil, rpc.ERRRESPONSE
	}
	return resp, nil
}
func (c *cconfigRpcClient) Cgroups(ctx context.Context, req *Cgroupsreq) (*Cgroupsresp, error) {
	if req == nil {
		return nil, rpc.ERRREQUEST
	}
	reqd, _ := proto.Marshal(req)
	callback, e := c.cc.Call(ctx, 500000000, RpcPathCconfigCgroups, reqd, metadata.GetAllMetadata(ctx))
	if e.(*error1.Error) != nil {
		return nil, e
	}
	resp := new(Cgroupsresp)
	if e := proto.Unmarshal(callback, resp); e != nil {
		return nil, rpc.ERRRESPONSE
	}
	return resp, nil
}
func (c *cconfigRpcClient) Capps(ctx context.Context, req *Cappsreq) (*Cappsresp, error) {
	if req == nil {
		return nil, rpc.ERRREQUEST
	}
	//empty check
	if len(req.Groupname) == 0 {
		return nil, rpc.ERRREQUEST
	}
	reqd, _ := proto.Marshal(req)
	callback, e := c.cc.Call(ctx, 500000000, RpcPathCconfigCapps, reqd, metadata.GetAllMetadata(ctx))
	if e.(*error1.Error) != nil {
		return nil, e
	}
	resp := new(Cappsresp)
	if e := proto.Unmarshal(callback, resp); e != nil {
		return nil, rpc.ERRRESPONSE
	}
	return resp, nil
}

// CconfigRpcServer is the server API for Cconfig service.
type CconfigRpcServer interface {
	//one specific app's current info
	Cinfo(context.Context, *Cinforeq) (*Cinforesp, error)
	//set one specific app's config
	Cset(context.Context, *Csetreq) (*Csetresp, error)
	//rollback one specific app's config
	Crollback(context.Context, *Crollbackreq) (*Crollbackresp, error)
	//get one specific app's config
	Cget(context.Context, *Cgetreq) (*Cgetresp, error)
	//get all groups
	Cgroups(context.Context, *Cgroupsreq) (*Cgroupsresp, error)
	//get all apps
	Capps(context.Context, *Cappsreq) (*Cappsresp, error)
}

func _Cconfig_Cinfo_RpcHandler(handler func(context.Context, *Cinforeq) (*Cinforesp, error)) rpc.OutsideHandler {
	return func(ctx *rpc.Context) {
		req := new(Cinforeq)
		if e := proto.Unmarshal(ctx.GetBody(), req); e != nil {
			ctx.Abort(rpc.ERRREQUEST)
			return
		}
		//empty check
		if len(req.Groupname) == 0 {
			ctx.Abort(rpc.ERRREQUEST)
			return
		}
		//empty check
		if len(req.Appname) == 0 {
			ctx.Abort(rpc.ERRREQUEST)
			return
		}
		//gte check
		if float64(req.OpNum) < 0 {
			ctx.Abort(rpc.ERRREQUEST)
			return
		}
		resp, e := handler(ctx, req)
		if e != nil {
			ctx.Abort(e)
			return
		}
		if resp == nil {
			resp = new(Cinforesp)
		}
		respd, _ := proto.Marshal(resp)
		ctx.Write(respd)
	}
}
func _Cconfig_Cset_RpcHandler(handler func(context.Context, *Csetreq) (*Csetresp, error)) rpc.OutsideHandler {
	return func(ctx *rpc.Context) {
		req := new(Csetreq)
		if e := proto.Unmarshal(ctx.GetBody(), req); e != nil {
			ctx.Abort(rpc.ERRREQUEST)
			return
		}
		//empty check
		if len(req.Groupname) == 0 {
			ctx.Abort(rpc.ERRREQUEST)
			return
		}
		//empty check
		if len(req.Appname) == 0 {
			ctx.Abort(rpc.ERRREQUEST)
			return
		}
		resp, e := handler(ctx, req)
		if e != nil {
			ctx.Abort(e)
			return
		}
		if resp == nil {
			resp = new(Csetresp)
		}
		respd, _ := proto.Marshal(resp)
		ctx.Write(respd)
	}
}
func _Cconfig_Crollback_RpcHandler(handler func(context.Context, *Crollbackreq) (*Crollbackresp, error)) rpc.OutsideHandler {
	return func(ctx *rpc.Context) {
		req := new(Crollbackreq)
		if e := proto.Unmarshal(ctx.GetBody(), req); e != nil {
			ctx.Abort(rpc.ERRREQUEST)
			return
		}
		//empty check
		if len(req.Groupname) == 0 {
			ctx.Abort(rpc.ERRREQUEST)
			return
		}
		//empty check
		if len(req.Appname) == 0 {
			ctx.Abort(rpc.ERRREQUEST)
			return
		}
		//empty check
		if len(req.Id) == 0 {
			ctx.Abort(rpc.ERRREQUEST)
			return
		}
		resp, e := handler(ctx, req)
		if e != nil {
			ctx.Abort(e)
			return
		}
		if resp == nil {
			resp = new(Crollbackresp)
		}
		respd, _ := proto.Marshal(resp)
		ctx.Write(respd)
	}
}
func _Cconfig_Cget_RpcHandler(handler func(context.Context, *Cgetreq) (*Cgetresp, error)) rpc.OutsideHandler {
	return func(ctx *rpc.Context) {
		req := new(Cgetreq)
		if e := proto.Unmarshal(ctx.GetBody(), req); e != nil {
			ctx.Abort(rpc.ERRREQUEST)
			return
		}
		//empty check
		if len(req.Groupname) == 0 {
			ctx.Abort(rpc.ERRREQUEST)
			return
		}
		//empty check
		if len(req.Appname) == 0 {
			ctx.Abort(rpc.ERRREQUEST)
			return
		}
		//empty check
		if len(req.Id) == 0 {
			ctx.Abort(rpc.ERRREQUEST)
			return
		}
		resp, e := handler(ctx, req)
		if e != nil {
			ctx.Abort(e)
			return
		}
		if resp == nil {
			resp = new(Cgetresp)
		}
		respd, _ := proto.Marshal(resp)
		ctx.Write(respd)
	}
}
func _Cconfig_Cgroups_RpcHandler(handler func(context.Context, *Cgroupsreq) (*Cgroupsresp, error)) rpc.OutsideHandler {
	return func(ctx *rpc.Context) {
		req := new(Cgroupsreq)
		if e := proto.Unmarshal(ctx.GetBody(), req); e != nil {
			ctx.Abort(rpc.ERRREQUEST)
			return
		}
		resp, e := handler(ctx, req)
		if e != nil {
			ctx.Abort(e)
			return
		}
		if resp == nil {
			resp = new(Cgroupsresp)
		}
		respd, _ := proto.Marshal(resp)
		ctx.Write(respd)
	}
}
func _Cconfig_Capps_RpcHandler(handler func(context.Context, *Cappsreq) (*Cappsresp, error)) rpc.OutsideHandler {
	return func(ctx *rpc.Context) {
		req := new(Cappsreq)
		if e := proto.Unmarshal(ctx.GetBody(), req); e != nil {
			ctx.Abort(rpc.ERRREQUEST)
			return
		}
		//empty check
		if len(req.Groupname) == 0 {
			ctx.Abort(rpc.ERRREQUEST)
			return
		}
		resp, e := handler(ctx, req)
		if e != nil {
			ctx.Abort(e)
			return
		}
		if resp == nil {
			resp = new(Cappsresp)
		}
		respd, _ := proto.Marshal(resp)
		ctx.Write(respd)
	}
}
func RegisterCconfigRpcServer(engine *rpc.RpcServer, svc CconfigRpcServer, allmids map[string]rpc.OutsideHandler) error {
	//avoid lint
	_ = allmids
	if e := engine.RegisterHandler(RpcPathCconfigCinfo, 500000000, _Cconfig_Cinfo_RpcHandler(svc.Cinfo)); e != nil {
		return e
	}
	if e := engine.RegisterHandler(RpcPathCconfigCset, 500000000, _Cconfig_Cset_RpcHandler(svc.Cset)); e != nil {
		return e
	}
	if e := engine.RegisterHandler(RpcPathCconfigCrollback, 500000000, _Cconfig_Crollback_RpcHandler(svc.Crollback)); e != nil {
		return e
	}
	if e := engine.RegisterHandler(RpcPathCconfigCget, 500000000, _Cconfig_Cget_RpcHandler(svc.Cget)); e != nil {
		return e
	}
	if e := engine.RegisterHandler(RpcPathCconfigCgroups, 500000000, _Cconfig_Cgroups_RpcHandler(svc.Cgroups)); e != nil {
		return e
	}
	if e := engine.RegisterHandler(RpcPathCconfigCapps, 500000000, _Cconfig_Capps_RpcHandler(svc.Capps)); e != nil {
		return e
	}
	return nil
}
