// Code generated by protoc-gen-go-pbex. DO NOT EDIT.
// version:
// 	protoc-gen-pbex v0.0.1
// 	protoc         v3.19.4
// source: api/config.proto

package api

//return empty means pass
func (m *AppsReq) Validate() (errstr string) {
	if len(m.GetGroupname()) <= 0 {
		return "field: groupname in object: apps_req check value str len gt failed"
	}
	return ""
}

//return empty means pass
func (m *GetReq) Validate() (errstr string) {
	if len(m.GetGroupname()) <= 0 {
		return "field: groupname in object: get_req check value str len gt failed"
	}
	if len(m.GetAppname()) <= 0 {
		return "field: appname in object: get_req check value str len gt failed"
	}
	return ""
}

//return empty means pass
func (m *SetReq) Validate() (errstr string) {
	if len(m.GetGroupname()) <= 0 {
		return "field: groupname in object: set_req check value str len gt failed"
	}
	if len(m.GetAppname()) <= 0 {
		return "field: appname in object: set_req check value str len gt failed"
	}
	return ""
}

//return empty means pass
func (m *RollbackReq) Validate() (errstr string) {
	if len(m.GetGroupname()) <= 0 {
		return "field: groupname in object: rollback_req check value str len gt failed"
	}
	if len(m.GetAppname()) <= 0 {
		return "field: appname in object: rollback_req check value str len gt failed"
	}
	if m.GetIndex() <= 0 {
		return "field: index in object: rollback_req check value uint gt failed"
	}
	return ""
}
