// Code generated by protoc-gen-go-rpc. DO NOT EDIT.
// version:
// 	protoc-gen-rpc v0.0.1
// 	protoc         v3.17.3
// source: api/sconfig.proto

package api

import (
	context "context"
	log "github.com/chenjie199234/Corelib/log"
	rpc "github.com/chenjie199234/Corelib/rpc"
	error1 "github.com/chenjie199234/Corelib/util/error"
	metadata "github.com/chenjie199234/Corelib/util/metadata"
	proto "google.golang.org/protobuf/proto"
)

var _SconfigRpcCheckers map[string]func(req interface{}) string

func init() {
	_SconfigRpcCheckers = make(map[string]func(req interface{}) string, 5)
	_SconfigRpcCheckers["\"\\\"Config/api\\\"\".SappsReq"] = func(r interface{}) string {
		req := r.(*SappsReq)
		if len(req.Groupname) <= 0 {
			return "field: groupname in object: sapps_req check value str len gt failed"
		}
		return ""
	}
	_SconfigRpcCheckers["\"\\\"Config/api\\\"\".SsetReq"] = func(r interface{}) string {
		req := r.(*SsetReq)
		if len(req.Groupname) <= 0 {
			return "field: groupname in object: sset_req check value str len gt failed"
		}
		if len(req.Appname) <= 0 {
			return "field: appname in object: sset_req check value str len gt failed"
		}
		return ""
	}
	_SconfigRpcCheckers["\"\\\"Config/api\\\"\".SgetReq"] = func(r interface{}) string {
		req := r.(*SgetReq)
		if len(req.Groupname) <= 0 {
			return "field: groupname in object: sget_req check value str len gt failed"
		}
		if len(req.Appname) <= 0 {
			return "field: appname in object: sget_req check value str len gt failed"
		}
		if req.Index <= 0 {
			return "field: index in object: sget_req check value uint gt failed"
		}
		return ""
	}
	_SconfigRpcCheckers["\"\\\"Config/api\\\"\".SinfoReq"] = func(r interface{}) string {
		req := r.(*SinfoReq)
		if len(req.Groupname) <= 0 {
			return "field: groupname in object: sinfo_req check value str len gt failed"
		}
		if len(req.Appname) <= 0 {
			return "field: appname in object: sinfo_req check value str len gt failed"
		}
		return ""
	}
	_SconfigRpcCheckers["\"\\\"Config/api\\\"\".SrollbackReq"] = func(r interface{}) string {
		req := r.(*SrollbackReq)
		if len(req.Groupname) <= 0 {
			return "field: groupname in object: srollback_req check value str len gt failed"
		}
		if len(req.Appname) <= 0 {
			return "field: appname in object: srollback_req check value str len gt failed"
		}
		if req.Index <= 0 {
			return "field: index in object: srollback_req check value uint gt failed"
		}
		return ""
	}
}

var _RpcPathSconfigSinfo = "/config.sconfig/sinfo"
var _RpcPathSconfigSset = "/config.sconfig/sset"
var _RpcPathSconfigSrollback = "/config.sconfig/srollback"
var _RpcPathSconfigSget = "/config.sconfig/sget"
var _RpcPathSconfigSgroups = "/config.sconfig/sgroups"
var _RpcPathSconfigSapps = "/config.sconfig/sapps"
var _RpcPathSconfigSwatchaddr = "/config.sconfig/swatchaddr"

type SconfigRpcClient interface {
	//one specific app's current info
	Sinfo(context.Context, *SinfoReq) (*SinfoResp, error)
	//set one specific app's config
	Sset(context.Context, *SsetReq) (*SsetResp, error)
	//rollback one specific app's config
	Srollback(context.Context, *SrollbackReq) (*SrollbackResp, error)
	//get one specific app's config
	Sget(context.Context, *SgetReq) (*SgetResp, error)
	//get all groups
	Sgroups(context.Context, *SgroupsReq) (*SgroupsResp, error)
	//get all apps
	Sapps(context.Context, *SappsReq) (*SappsResp, error)
	//get watch addr
	Swatchaddr(context.Context, *SwatchaddrReq) (*SwatchaddrResp, error)
}

type sconfigRpcClient struct {
	cc *rpc.RpcClient
}

func NewSconfigRpcClient(c *rpc.ClientConfig, selfgroup, selfname, peergroup, peername string) (SconfigRpcClient, error) {
	cc, e := rpc.NewRpcClient(c, selfgroup, selfname, peergroup, peername)
	if e != nil {
		return nil, e
	}
	return &sconfigRpcClient{cc: cc}, nil
}

func (c *sconfigRpcClient) Sinfo(ctx context.Context, req *SinfoReq) (*SinfoResp, error) {
	if req == nil {
		return nil, error1.ErrReq
	}
	if s := _SconfigRpcCheckers["\"\\\"Config/api\\\"\".SinfoReq"](req); s != "" {
		log.Error("[/config.sconfig/sinfo]", s)
		return nil, error1.ErrReq
	}
	reqd, _ := proto.Marshal(req)
	respd, e := c.cc.Call(ctx, 250000000, _RpcPathSconfigSinfo, reqd, metadata.GetAllMetadata(ctx))
	if e != nil {
		return nil, error1.StdErrorToError(e)
	}
	resp := new(SinfoResp)
	if len(respd) == 0 {
		return resp, nil
	}
	if e := proto.Unmarshal(respd, resp); e != nil {
		return nil, error1.ErrResp
	}
	return resp, nil
}
func (c *sconfigRpcClient) Sset(ctx context.Context, req *SsetReq) (*SsetResp, error) {
	if req == nil {
		return nil, error1.ErrReq
	}
	if s := _SconfigRpcCheckers["\"\\\"Config/api\\\"\".SsetReq"](req); s != "" {
		log.Error("[/config.sconfig/sset]", s)
		return nil, error1.ErrReq
	}
	reqd, _ := proto.Marshal(req)
	respd, e := c.cc.Call(ctx, 250000000, _RpcPathSconfigSset, reqd, metadata.GetAllMetadata(ctx))
	if e != nil {
		return nil, error1.StdErrorToError(e)
	}
	resp := new(SsetResp)
	if len(respd) == 0 {
		return resp, nil
	}
	if e := proto.Unmarshal(respd, resp); e != nil {
		return nil, error1.ErrResp
	}
	return resp, nil
}
func (c *sconfigRpcClient) Srollback(ctx context.Context, req *SrollbackReq) (*SrollbackResp, error) {
	if req == nil {
		return nil, error1.ErrReq
	}
	if s := _SconfigRpcCheckers["\"\\\"Config/api\\\"\".SrollbackReq"](req); s != "" {
		log.Error("[/config.sconfig/srollback]", s)
		return nil, error1.ErrReq
	}
	reqd, _ := proto.Marshal(req)
	respd, e := c.cc.Call(ctx, 250000000, _RpcPathSconfigSrollback, reqd, metadata.GetAllMetadata(ctx))
	if e != nil {
		return nil, error1.StdErrorToError(e)
	}
	resp := new(SrollbackResp)
	if len(respd) == 0 {
		return resp, nil
	}
	if e := proto.Unmarshal(respd, resp); e != nil {
		return nil, error1.ErrResp
	}
	return resp, nil
}
func (c *sconfigRpcClient) Sget(ctx context.Context, req *SgetReq) (*SgetResp, error) {
	if req == nil {
		return nil, error1.ErrReq
	}
	if s := _SconfigRpcCheckers["\"\\\"Config/api\\\"\".SgetReq"](req); s != "" {
		log.Error("[/config.sconfig/sget]", s)
		return nil, error1.ErrReq
	}
	reqd, _ := proto.Marshal(req)
	respd, e := c.cc.Call(ctx, 250000000, _RpcPathSconfigSget, reqd, metadata.GetAllMetadata(ctx))
	if e != nil {
		return nil, error1.StdErrorToError(e)
	}
	resp := new(SgetResp)
	if len(respd) == 0 {
		return resp, nil
	}
	if e := proto.Unmarshal(respd, resp); e != nil {
		return nil, error1.ErrResp
	}
	return resp, nil
}
func (c *sconfigRpcClient) Sgroups(ctx context.Context, req *SgroupsReq) (*SgroupsResp, error) {
	if req == nil {
		return nil, error1.ErrReq
	}
	reqd, _ := proto.Marshal(req)
	respd, e := c.cc.Call(ctx, 250000000, _RpcPathSconfigSgroups, reqd, metadata.GetAllMetadata(ctx))
	if e != nil {
		return nil, error1.StdErrorToError(e)
	}
	resp := new(SgroupsResp)
	if len(respd) == 0 {
		return resp, nil
	}
	if e := proto.Unmarshal(respd, resp); e != nil {
		return nil, error1.ErrResp
	}
	return resp, nil
}
func (c *sconfigRpcClient) Sapps(ctx context.Context, req *SappsReq) (*SappsResp, error) {
	if req == nil {
		return nil, error1.ErrReq
	}
	if s := _SconfigRpcCheckers["\"\\\"Config/api\\\"\".SappsReq"](req); s != "" {
		log.Error("[/config.sconfig/sapps]", s)
		return nil, error1.ErrReq
	}
	reqd, _ := proto.Marshal(req)
	respd, e := c.cc.Call(ctx, 250000000, _RpcPathSconfigSapps, reqd, metadata.GetAllMetadata(ctx))
	if e != nil {
		return nil, error1.StdErrorToError(e)
	}
	resp := new(SappsResp)
	if len(respd) == 0 {
		return resp, nil
	}
	if e := proto.Unmarshal(respd, resp); e != nil {
		return nil, error1.ErrResp
	}
	return resp, nil
}
func (c *sconfigRpcClient) Swatchaddr(ctx context.Context, req *SwatchaddrReq) (*SwatchaddrResp, error) {
	if req == nil {
		return nil, error1.ErrReq
	}
	reqd, _ := proto.Marshal(req)
	respd, e := c.cc.Call(ctx, 250000000, _RpcPathSconfigSwatchaddr, reqd, metadata.GetAllMetadata(ctx))
	if e != nil {
		return nil, error1.StdErrorToError(e)
	}
	resp := new(SwatchaddrResp)
	if len(respd) == 0 {
		return resp, nil
	}
	if e := proto.Unmarshal(respd, resp); e != nil {
		return nil, error1.ErrResp
	}
	return resp, nil
}

type SconfigRpcServer interface {
	//one specific app's current info
	Sinfo(context.Context, *SinfoReq) (*SinfoResp, error)
	//set one specific app's config
	Sset(context.Context, *SsetReq) (*SsetResp, error)
	//rollback one specific app's config
	Srollback(context.Context, *SrollbackReq) (*SrollbackResp, error)
	//get one specific app's config
	Sget(context.Context, *SgetReq) (*SgetResp, error)
	//get all groups
	Sgroups(context.Context, *SgroupsReq) (*SgroupsResp, error)
	//get all apps
	Sapps(context.Context, *SappsReq) (*SappsResp, error)
	//get watch addr
	Swatchaddr(context.Context, *SwatchaddrReq) (*SwatchaddrResp, error)
}

func _Sconfig_Sinfo_RpcHandler(handler func(context.Context, *SinfoReq) (*SinfoResp, error)) rpc.OutsideHandler {
	return func(ctx *rpc.Context) {
		req := new(SinfoReq)
		if e := proto.Unmarshal(ctx.GetBody(), req); e != nil {
			ctx.Abort(error1.ErrReq)
			return
		}
		if s := _SconfigRpcCheckers["\"\\\"Config/api\\\"\".SinfoReq"](req); s != "" {
			log.Error("[/config.sconfig/sinfo]", s)
			ctx.Abort(error1.ErrReq)
		}
		resp, e := handler(ctx, req)
		if e != nil {
			ctx.Abort(e)
			return
		}
		if resp == nil {
			resp = new(SinfoResp)
		}
		respd, _ := proto.Marshal(resp)
		ctx.Write(respd)
	}
}
func _Sconfig_Sset_RpcHandler(handler func(context.Context, *SsetReq) (*SsetResp, error)) rpc.OutsideHandler {
	return func(ctx *rpc.Context) {
		req := new(SsetReq)
		if e := proto.Unmarshal(ctx.GetBody(), req); e != nil {
			ctx.Abort(error1.ErrReq)
			return
		}
		if s := _SconfigRpcCheckers["\"\\\"Config/api\\\"\".SsetReq"](req); s != "" {
			log.Error("[/config.sconfig/sset]", s)
			ctx.Abort(error1.ErrReq)
		}
		resp, e := handler(ctx, req)
		if e != nil {
			ctx.Abort(e)
			return
		}
		if resp == nil {
			resp = new(SsetResp)
		}
		respd, _ := proto.Marshal(resp)
		ctx.Write(respd)
	}
}
func _Sconfig_Srollback_RpcHandler(handler func(context.Context, *SrollbackReq) (*SrollbackResp, error)) rpc.OutsideHandler {
	return func(ctx *rpc.Context) {
		req := new(SrollbackReq)
		if e := proto.Unmarshal(ctx.GetBody(), req); e != nil {
			ctx.Abort(error1.ErrReq)
			return
		}
		if s := _SconfigRpcCheckers["\"\\\"Config/api\\\"\".SrollbackReq"](req); s != "" {
			log.Error("[/config.sconfig/srollback]", s)
			ctx.Abort(error1.ErrReq)
		}
		resp, e := handler(ctx, req)
		if e != nil {
			ctx.Abort(e)
			return
		}
		if resp == nil {
			resp = new(SrollbackResp)
		}
		respd, _ := proto.Marshal(resp)
		ctx.Write(respd)
	}
}
func _Sconfig_Sget_RpcHandler(handler func(context.Context, *SgetReq) (*SgetResp, error)) rpc.OutsideHandler {
	return func(ctx *rpc.Context) {
		req := new(SgetReq)
		if e := proto.Unmarshal(ctx.GetBody(), req); e != nil {
			ctx.Abort(error1.ErrReq)
			return
		}
		if s := _SconfigRpcCheckers["\"\\\"Config/api\\\"\".SgetReq"](req); s != "" {
			log.Error("[/config.sconfig/sget]", s)
			ctx.Abort(error1.ErrReq)
		}
		resp, e := handler(ctx, req)
		if e != nil {
			ctx.Abort(e)
			return
		}
		if resp == nil {
			resp = new(SgetResp)
		}
		respd, _ := proto.Marshal(resp)
		ctx.Write(respd)
	}
}
func _Sconfig_Sgroups_RpcHandler(handler func(context.Context, *SgroupsReq) (*SgroupsResp, error)) rpc.OutsideHandler {
	return func(ctx *rpc.Context) {
		req := new(SgroupsReq)
		if e := proto.Unmarshal(ctx.GetBody(), req); e != nil {
			ctx.Abort(error1.ErrReq)
			return
		}
		resp, e := handler(ctx, req)
		if e != nil {
			ctx.Abort(e)
			return
		}
		if resp == nil {
			resp = new(SgroupsResp)
		}
		respd, _ := proto.Marshal(resp)
		ctx.Write(respd)
	}
}
func _Sconfig_Sapps_RpcHandler(handler func(context.Context, *SappsReq) (*SappsResp, error)) rpc.OutsideHandler {
	return func(ctx *rpc.Context) {
		req := new(SappsReq)
		if e := proto.Unmarshal(ctx.GetBody(), req); e != nil {
			ctx.Abort(error1.ErrReq)
			return
		}
		if s := _SconfigRpcCheckers["\"\\\"Config/api\\\"\".SappsReq"](req); s != "" {
			log.Error("[/config.sconfig/sapps]", s)
			ctx.Abort(error1.ErrReq)
		}
		resp, e := handler(ctx, req)
		if e != nil {
			ctx.Abort(e)
			return
		}
		if resp == nil {
			resp = new(SappsResp)
		}
		respd, _ := proto.Marshal(resp)
		ctx.Write(respd)
	}
}
func _Sconfig_Swatchaddr_RpcHandler(handler func(context.Context, *SwatchaddrReq) (*SwatchaddrResp, error)) rpc.OutsideHandler {
	return func(ctx *rpc.Context) {
		req := new(SwatchaddrReq)
		if e := proto.Unmarshal(ctx.GetBody(), req); e != nil {
			ctx.Abort(error1.ErrReq)
			return
		}
		resp, e := handler(ctx, req)
		if e != nil {
			ctx.Abort(e)
			return
		}
		if resp == nil {
			resp = new(SwatchaddrResp)
		}
		respd, _ := proto.Marshal(resp)
		ctx.Write(respd)
	}
}
func RegisterSconfigRpcServer(engine *rpc.RpcServer, svc SconfigRpcServer, allmids map[string]rpc.OutsideHandler) error {
	//avoid lint
	_ = allmids
	if e := engine.RegisterHandler(_RpcPathSconfigSinfo, 250000000, _Sconfig_Sinfo_RpcHandler(svc.Sinfo)); e != nil {
		return e
	}
	if e := engine.RegisterHandler(_RpcPathSconfigSset, 250000000, _Sconfig_Sset_RpcHandler(svc.Sset)); e != nil {
		return e
	}
	if e := engine.RegisterHandler(_RpcPathSconfigSrollback, 250000000, _Sconfig_Srollback_RpcHandler(svc.Srollback)); e != nil {
		return e
	}
	if e := engine.RegisterHandler(_RpcPathSconfigSget, 250000000, _Sconfig_Sget_RpcHandler(svc.Sget)); e != nil {
		return e
	}
	if e := engine.RegisterHandler(_RpcPathSconfigSgroups, 250000000, _Sconfig_Sgroups_RpcHandler(svc.Sgroups)); e != nil {
		return e
	}
	if e := engine.RegisterHandler(_RpcPathSconfigSapps, 250000000, _Sconfig_Sapps_RpcHandler(svc.Sapps)); e != nil {
		return e
	}
	if e := engine.RegisterHandler(_RpcPathSconfigSwatchaddr, 250000000, _Sconfig_Swatchaddr_RpcHandler(svc.Swatchaddr)); e != nil {
		return e
	}
	return nil
}
