// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: api/sconfig.proto

//this is the proto package name,all proto in this project must use this name as the proto package name

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sinforeq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groupname string `protobuf:"bytes,1,opt,name=groupname,proto3" json:"groupname,omitempty"` //empty:false
	Appname   string `protobuf:"bytes,2,opt,name=appname,proto3" json:"appname,omitempty"`     //empty:false
	//check if need update
	//if not,only op_num field will return
	//0 will always return all data
	OpNum int64 `protobuf:"varint,3,opt,name=op_num,json=opNum,proto3" json:"op_num,omitempty"` //gte:0
}

func (x *Sinforeq) Reset() {
	*x = Sinforeq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sconfig_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sinforeq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sinforeq) ProtoMessage() {}

func (x *Sinforeq) ProtoReflect() protoreflect.Message {
	mi := &file_api_sconfig_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sinforeq.ProtoReflect.Descriptor instead.
func (*Sinforeq) Descriptor() ([]byte, []int) {
	return file_api_sconfig_proto_rawDescGZIP(), []int{0}
}

func (x *Sinforeq) GetGroupname() string {
	if x != nil {
		return x.Groupname
	}
	return ""
}

func (x *Sinforeq) GetAppname() string {
	if x != nil {
		return x.Appname
	}
	return ""
}

func (x *Sinforeq) GetOpNum() int64 {
	if x != nil {
		return x.OpNum
	}
	return 0
}

type Sinforesp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurId           string `protobuf:"bytes,1,opt,name=cur_id,json=curId,proto3" json:"cur_id,omitempty"`
	CurAppConfig    string `protobuf:"bytes,2,opt,name=cur_app_config,json=curAppConfig,proto3" json:"cur_app_config,omitempty"`
	CurSourceConfig string `protobuf:"bytes,3,opt,name=cur_source_config,json=curSourceConfig,proto3" json:"cur_source_config,omitempty"`
	OpNum           int64  `protobuf:"varint,4,opt,name=op_num,json=opNum,proto3" json:"op_num,omitempty"`
	//ids are sortted by create time
	AllIds []string `protobuf:"bytes,5,rep,name=all_ids,json=allIds,proto3" json:"all_ids,omitempty"`
}

func (x *Sinforesp) Reset() {
	*x = Sinforesp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sconfig_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sinforesp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sinforesp) ProtoMessage() {}

func (x *Sinforesp) ProtoReflect() protoreflect.Message {
	mi := &file_api_sconfig_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sinforesp.ProtoReflect.Descriptor instead.
func (*Sinforesp) Descriptor() ([]byte, []int) {
	return file_api_sconfig_proto_rawDescGZIP(), []int{1}
}

func (x *Sinforesp) GetCurId() string {
	if x != nil {
		return x.CurId
	}
	return ""
}

func (x *Sinforesp) GetCurAppConfig() string {
	if x != nil {
		return x.CurAppConfig
	}
	return ""
}

func (x *Sinforesp) GetCurSourceConfig() string {
	if x != nil {
		return x.CurSourceConfig
	}
	return ""
}

func (x *Sinforesp) GetOpNum() int64 {
	if x != nil {
		return x.OpNum
	}
	return 0
}

func (x *Sinforesp) GetAllIds() []string {
	if x != nil {
		return x.AllIds
	}
	return nil
}

type Ssetreq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groupname    string `protobuf:"bytes,1,opt,name=groupname,proto3" json:"groupname,omitempty"` //empty:false
	Appname      string `protobuf:"bytes,2,opt,name=appname,proto3" json:"appname,omitempty"`     //empty:false
	AppConfig    string `protobuf:"bytes,3,opt,name=app_config,json=appConfig,proto3" json:"app_config,omitempty"`
	SourceConfig string `protobuf:"bytes,4,opt,name=source_config,json=sourceConfig,proto3" json:"source_config,omitempty"`
}

func (x *Ssetreq) Reset() {
	*x = Ssetreq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sconfig_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ssetreq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ssetreq) ProtoMessage() {}

func (x *Ssetreq) ProtoReflect() protoreflect.Message {
	mi := &file_api_sconfig_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ssetreq.ProtoReflect.Descriptor instead.
func (*Ssetreq) Descriptor() ([]byte, []int) {
	return file_api_sconfig_proto_rawDescGZIP(), []int{2}
}

func (x *Ssetreq) GetGroupname() string {
	if x != nil {
		return x.Groupname
	}
	return ""
}

func (x *Ssetreq) GetAppname() string {
	if x != nil {
		return x.Appname
	}
	return ""
}

func (x *Ssetreq) GetAppConfig() string {
	if x != nil {
		return x.AppConfig
	}
	return ""
}

func (x *Ssetreq) GetSourceConfig() string {
	if x != nil {
		return x.SourceConfig
	}
	return ""
}

type Ssetresp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ssetresp) Reset() {
	*x = Ssetresp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sconfig_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ssetresp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ssetresp) ProtoMessage() {}

func (x *Ssetresp) ProtoReflect() protoreflect.Message {
	mi := &file_api_sconfig_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ssetresp.ProtoReflect.Descriptor instead.
func (*Ssetresp) Descriptor() ([]byte, []int) {
	return file_api_sconfig_proto_rawDescGZIP(), []int{3}
}

type Srollbackreq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groupname string `protobuf:"bytes,1,opt,name=groupname,proto3" json:"groupname,omitempty"` //empty:false
	Appname   string `protobuf:"bytes,2,opt,name=appname,proto3" json:"appname,omitempty"`     //empty:false
	Id        string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`               //empty:false
}

func (x *Srollbackreq) Reset() {
	*x = Srollbackreq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sconfig_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Srollbackreq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Srollbackreq) ProtoMessage() {}

func (x *Srollbackreq) ProtoReflect() protoreflect.Message {
	mi := &file_api_sconfig_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Srollbackreq.ProtoReflect.Descriptor instead.
func (*Srollbackreq) Descriptor() ([]byte, []int) {
	return file_api_sconfig_proto_rawDescGZIP(), []int{4}
}

func (x *Srollbackreq) GetGroupname() string {
	if x != nil {
		return x.Groupname
	}
	return ""
}

func (x *Srollbackreq) GetAppname() string {
	if x != nil {
		return x.Appname
	}
	return ""
}

func (x *Srollbackreq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Srollbackresp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Srollbackresp) Reset() {
	*x = Srollbackresp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sconfig_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Srollbackresp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Srollbackresp) ProtoMessage() {}

func (x *Srollbackresp) ProtoReflect() protoreflect.Message {
	mi := &file_api_sconfig_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Srollbackresp.ProtoReflect.Descriptor instead.
func (*Srollbackresp) Descriptor() ([]byte, []int) {
	return file_api_sconfig_proto_rawDescGZIP(), []int{5}
}

type Sgetreq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groupname string `protobuf:"bytes,1,opt,name=groupname,proto3" json:"groupname,omitempty"` //empty:false
	Appname   string `protobuf:"bytes,2,opt,name=appname,proto3" json:"appname,omitempty"`     //empty:false
	Id        string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`               //empty:false
}

func (x *Sgetreq) Reset() {
	*x = Sgetreq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sconfig_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sgetreq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sgetreq) ProtoMessage() {}

func (x *Sgetreq) ProtoReflect() protoreflect.Message {
	mi := &file_api_sconfig_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sgetreq.ProtoReflect.Descriptor instead.
func (*Sgetreq) Descriptor() ([]byte, []int) {
	return file_api_sconfig_proto_rawDescGZIP(), []int{6}
}

func (x *Sgetreq) GetGroupname() string {
	if x != nil {
		return x.Groupname
	}
	return ""
}

func (x *Sgetreq) GetAppname() string {
	if x != nil {
		return x.Appname
	}
	return ""
}

func (x *Sgetreq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Sgetresp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppConfig    string `protobuf:"bytes,2,opt,name=app_config,json=appConfig,proto3" json:"app_config,omitempty"`
	SourceConfig string `protobuf:"bytes,3,opt,name=source_config,json=sourceConfig,proto3" json:"source_config,omitempty"`
}

func (x *Sgetresp) Reset() {
	*x = Sgetresp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sconfig_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sgetresp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sgetresp) ProtoMessage() {}

func (x *Sgetresp) ProtoReflect() protoreflect.Message {
	mi := &file_api_sconfig_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sgetresp.ProtoReflect.Descriptor instead.
func (*Sgetresp) Descriptor() ([]byte, []int) {
	return file_api_sconfig_proto_rawDescGZIP(), []int{7}
}

func (x *Sgetresp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Sgetresp) GetAppConfig() string {
	if x != nil {
		return x.AppConfig
	}
	return ""
}

func (x *Sgetresp) GetSourceConfig() string {
	if x != nil {
		return x.SourceConfig
	}
	return ""
}

type Sgroupsreq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Sgroupsreq) Reset() {
	*x = Sgroupsreq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sconfig_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sgroupsreq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sgroupsreq) ProtoMessage() {}

func (x *Sgroupsreq) ProtoReflect() protoreflect.Message {
	mi := &file_api_sconfig_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sgroupsreq.ProtoReflect.Descriptor instead.
func (*Sgroupsreq) Descriptor() ([]byte, []int) {
	return file_api_sconfig_proto_rawDescGZIP(), []int{8}
}

type Sgroupsresp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groups []string `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *Sgroupsresp) Reset() {
	*x = Sgroupsresp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sconfig_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sgroupsresp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sgroupsresp) ProtoMessage() {}

func (x *Sgroupsresp) ProtoReflect() protoreflect.Message {
	mi := &file_api_sconfig_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sgroupsresp.ProtoReflect.Descriptor instead.
func (*Sgroupsresp) Descriptor() ([]byte, []int) {
	return file_api_sconfig_proto_rawDescGZIP(), []int{9}
}

func (x *Sgroupsresp) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

type Sappsreq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groupname string `protobuf:"bytes,1,opt,name=groupname,proto3" json:"groupname,omitempty"` //empty:false
}

func (x *Sappsreq) Reset() {
	*x = Sappsreq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sconfig_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sappsreq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sappsreq) ProtoMessage() {}

func (x *Sappsreq) ProtoReflect() protoreflect.Message {
	mi := &file_api_sconfig_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sappsreq.ProtoReflect.Descriptor instead.
func (*Sappsreq) Descriptor() ([]byte, []int) {
	return file_api_sconfig_proto_rawDescGZIP(), []int{10}
}

func (x *Sappsreq) GetGroupname() string {
	if x != nil {
		return x.Groupname
	}
	return ""
}

type Sappsresp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Apps []string `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
}

func (x *Sappsresp) Reset() {
	*x = Sappsresp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sconfig_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sappsresp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sappsresp) ProtoMessage() {}

func (x *Sappsresp) ProtoReflect() protoreflect.Message {
	mi := &file_api_sconfig_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sappsresp.ProtoReflect.Descriptor instead.
func (*Sappsresp) Descriptor() ([]byte, []int) {
	return file_api_sconfig_proto_rawDescGZIP(), []int{11}
}

func (x *Sappsresp) GetApps() []string {
	if x != nil {
		return x.Apps
	}
	return nil
}

type Ssetwatchaddrreq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username       string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Passwd         string   `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	Addrs          []string `protobuf:"bytes,3,rep,name=addrs,proto3" json:"addrs,omitempty"`
	ReplicaSetName string   `protobuf:"bytes,4,opt,name=replica_set_name,json=replicaSetName,proto3" json:"replica_set_name,omitempty"`
}

func (x *Ssetwatchaddrreq) Reset() {
	*x = Ssetwatchaddrreq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sconfig_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ssetwatchaddrreq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ssetwatchaddrreq) ProtoMessage() {}

func (x *Ssetwatchaddrreq) ProtoReflect() protoreflect.Message {
	mi := &file_api_sconfig_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ssetwatchaddrreq.ProtoReflect.Descriptor instead.
func (*Ssetwatchaddrreq) Descriptor() ([]byte, []int) {
	return file_api_sconfig_proto_rawDescGZIP(), []int{12}
}

func (x *Ssetwatchaddrreq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Ssetwatchaddrreq) GetPasswd() string {
	if x != nil {
		return x.Passwd
	}
	return ""
}

func (x *Ssetwatchaddrreq) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *Ssetwatchaddrreq) GetReplicaSetName() string {
	if x != nil {
		return x.ReplicaSetName
	}
	return ""
}

type Ssetwatchaddrresp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ssetwatchaddrresp) Reset() {
	*x = Ssetwatchaddrresp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sconfig_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ssetwatchaddrresp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ssetwatchaddrresp) ProtoMessage() {}

func (x *Ssetwatchaddrresp) ProtoReflect() protoreflect.Message {
	mi := &file_api_sconfig_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ssetwatchaddrresp.ProtoReflect.Descriptor instead.
func (*Ssetwatchaddrresp) Descriptor() ([]byte, []int) {
	return file_api_sconfig_proto_rawDescGZIP(), []int{13}
}

type Sgetwatchaddrreq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Sgetwatchaddrreq) Reset() {
	*x = Sgetwatchaddrreq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sconfig_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sgetwatchaddrreq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sgetwatchaddrreq) ProtoMessage() {}

func (x *Sgetwatchaddrreq) ProtoReflect() protoreflect.Message {
	mi := &file_api_sconfig_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sgetwatchaddrreq.ProtoReflect.Descriptor instead.
func (*Sgetwatchaddrreq) Descriptor() ([]byte, []int) {
	return file_api_sconfig_proto_rawDescGZIP(), []int{14}
}

type Sgetwatchaddrresp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username       string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Passwd         string   `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	Addrs          []string `protobuf:"bytes,3,rep,name=addrs,proto3" json:"addrs,omitempty"`
	ReplicaSetName string   `protobuf:"bytes,4,opt,name=replica_set_name,json=replicaSetName,proto3" json:"replica_set_name,omitempty"`
}

func (x *Sgetwatchaddrresp) Reset() {
	*x = Sgetwatchaddrresp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sconfig_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sgetwatchaddrresp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sgetwatchaddrresp) ProtoMessage() {}

func (x *Sgetwatchaddrresp) ProtoReflect() protoreflect.Message {
	mi := &file_api_sconfig_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sgetwatchaddrresp.ProtoReflect.Descriptor instead.
func (*Sgetwatchaddrresp) Descriptor() ([]byte, []int) {
	return file_api_sconfig_proto_rawDescGZIP(), []int{15}
}

func (x *Sgetwatchaddrresp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Sgetwatchaddrresp) GetPasswd() string {
	if x != nil {
		return x.Passwd
	}
	return ""
}

func (x *Sgetwatchaddrresp) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *Sgetwatchaddrresp) GetReplicaSetName() string {
	if x != nil {
		return x.ReplicaSetName
	}
	return ""
}

var File_api_sconfig_proto protoreflect.FileDescriptor

var file_api_sconfig_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x59, 0x0a, 0x08, 0x73,
	0x69, 0x6e, 0x66, 0x6f, 0x72, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x15, 0x0a, 0x06, 0x6f, 0x70, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x6f, 0x70, 0x4e, 0x75, 0x6d, 0x22, 0xa4, 0x01, 0x0a, 0x09, 0x73, 0x69, 0x6e, 0x66, 0x6f,
	0x72, 0x65, 0x73, 0x70, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x75, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x75, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x63,
	0x75, 0x72, 0x5f, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x2a, 0x0a, 0x11, 0x63, 0x75, 0x72, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x75,
	0x72, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x15, 0x0a,
	0x06, 0x6f, 0x70, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f,
	0x70, 0x4e, 0x75, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x73, 0x22, 0x85, 0x01,
	0x0a, 0x07, 0x73, 0x73, 0x65, 0x74, 0x72, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x23, 0x0a, 0x0d, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x0a, 0x0a, 0x08, 0x73, 0x73, 0x65, 0x74, 0x72, 0x65, 0x73,
	0x70, 0x22, 0x56, 0x0a, 0x0c, 0x73, 0x72, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x72, 0x65,
	0x71, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x70, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x73, 0x72, 0x6f,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x72, 0x65, 0x73, 0x70, 0x22, 0x51, 0x0a, 0x07, 0x73, 0x67,
	0x65, 0x74, 0x72, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5e, 0x0a,
	0x08, 0x73, 0x67, 0x65, 0x74, 0x72, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x70, 0x70,
	0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61,
	0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x0c, 0x0a,
	0x0a, 0x73, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x72, 0x65, 0x71, 0x22, 0x25, 0x0a, 0x0b, 0x73,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x72, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x22, 0x28, 0x0a, 0x08, 0x73, 0x61, 0x70, 0x70, 0x73, 0x72, 0x65, 0x71, 0x12, 0x1c,
	0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1f, 0x0a, 0x09,
	0x73, 0x61, 0x70, 0x70, 0x73, 0x72, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x70, 0x70,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x70, 0x70, 0x73, 0x22, 0x86, 0x01,
	0x0a, 0x10, 0x73, 0x73, 0x65, 0x74, 0x77, 0x61, 0x74, 0x63, 0x68, 0x61, 0x64, 0x64, 0x72, 0x72,
	0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x12, 0x28, 0x0a, 0x10,
	0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x53,
	0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x73, 0x73, 0x65, 0x74, 0x77, 0x61,
	0x74, 0x63, 0x68, 0x61, 0x64, 0x64, 0x72, 0x72, 0x65, 0x73, 0x70, 0x22, 0x12, 0x0a, 0x10, 0x73,
	0x67, 0x65, 0x74, 0x77, 0x61, 0x74, 0x63, 0x68, 0x61, 0x64, 0x64, 0x72, 0x72, 0x65, 0x71, 0x22,
	0x87, 0x01, 0x0a, 0x11, 0x73, 0x67, 0x65, 0x74, 0x77, 0x61, 0x74, 0x63, 0x68, 0x61, 0x64, 0x64,
	0x72, 0x72, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64,
	0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x12,
	0x28, 0x0a, 0x10, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x53, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0xb5, 0x03, 0x0a, 0x07, 0x73, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2c, 0x0a, 0x05, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x10,
	0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x65, 0x71,
	0x1a, 0x11, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x72,
	0x65, 0x73, 0x70, 0x12, 0x29, 0x0a, 0x04, 0x73, 0x73, 0x65, 0x74, 0x12, 0x0f, 0x2e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x73, 0x73, 0x65, 0x74, 0x72, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x73, 0x73, 0x65, 0x74, 0x72, 0x65, 0x73, 0x70, 0x12, 0x38,
	0x0a, 0x09, 0x73, 0x72, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x14, 0x2e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x73, 0x72, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x72, 0x65,
	0x71, 0x1a, 0x15, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x73, 0x72, 0x6f, 0x6c, 0x6c,
	0x62, 0x61, 0x63, 0x6b, 0x72, 0x65, 0x73, 0x70, 0x12, 0x29, 0x0a, 0x04, 0x73, 0x67, 0x65, 0x74,
	0x12, 0x0f, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x73, 0x67, 0x65, 0x74, 0x72, 0x65,
	0x71, 0x1a, 0x10, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x73, 0x67, 0x65, 0x74, 0x72,
	0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x07, 0x73, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x12,
	0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x73, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x72,
	0x65, 0x71, 0x1a, 0x13, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x73, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x73, 0x72, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x05, 0x73, 0x61, 0x70, 0x70, 0x73,
	0x12, 0x10, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x73, 0x61, 0x70, 0x70, 0x73, 0x72,
	0x65, 0x71, 0x1a, 0x11, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x73, 0x61, 0x70, 0x70,
	0x73, 0x72, 0x65, 0x73, 0x70, 0x12, 0x44, 0x0a, 0x0d, 0x73, 0x73, 0x65, 0x74, 0x77, 0x61, 0x74,
	0x63, 0x68, 0x61, 0x64, 0x64, 0x72, 0x12, 0x18, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x73, 0x73, 0x65, 0x74, 0x77, 0x61, 0x74, 0x63, 0x68, 0x61, 0x64, 0x64, 0x72, 0x72, 0x65, 0x71,
	0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x73, 0x73, 0x65, 0x74, 0x77, 0x61,
	0x74, 0x63, 0x68, 0x61, 0x64, 0x64, 0x72, 0x72, 0x65, 0x73, 0x70, 0x12, 0x44, 0x0a, 0x0d, 0x73,
	0x67, 0x65, 0x74, 0x77, 0x61, 0x74, 0x63, 0x68, 0x61, 0x64, 0x64, 0x72, 0x12, 0x18, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x73, 0x67, 0x65, 0x74, 0x77, 0x61, 0x74, 0x63, 0x68, 0x61,
	0x64, 0x64, 0x72, 0x72, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x73, 0x67, 0x65, 0x74, 0x77, 0x61, 0x74, 0x63, 0x68, 0x61, 0x64, 0x64, 0x72, 0x72, 0x65, 0x73,
	0x70, 0x42, 0x10, 0x5a, 0x0e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x3b,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_sconfig_proto_rawDescOnce sync.Once
	file_api_sconfig_proto_rawDescData = file_api_sconfig_proto_rawDesc
)

func file_api_sconfig_proto_rawDescGZIP() []byte {
	file_api_sconfig_proto_rawDescOnce.Do(func() {
		file_api_sconfig_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_sconfig_proto_rawDescData)
	})
	return file_api_sconfig_proto_rawDescData
}

var file_api_sconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_sconfig_proto_goTypes = []interface{}{
	(*Sinforeq)(nil),          // 0: config.sinforeq
	(*Sinforesp)(nil),         // 1: config.sinforesp
	(*Ssetreq)(nil),           // 2: config.ssetreq
	(*Ssetresp)(nil),          // 3: config.ssetresp
	(*Srollbackreq)(nil),      // 4: config.srollbackreq
	(*Srollbackresp)(nil),     // 5: config.srollbackresp
	(*Sgetreq)(nil),           // 6: config.sgetreq
	(*Sgetresp)(nil),          // 7: config.sgetresp
	(*Sgroupsreq)(nil),        // 8: config.sgroupsreq
	(*Sgroupsresp)(nil),       // 9: config.sgroupsresp
	(*Sappsreq)(nil),          // 10: config.sappsreq
	(*Sappsresp)(nil),         // 11: config.sappsresp
	(*Ssetwatchaddrreq)(nil),  // 12: config.ssetwatchaddrreq
	(*Ssetwatchaddrresp)(nil), // 13: config.ssetwatchaddrresp
	(*Sgetwatchaddrreq)(nil),  // 14: config.sgetwatchaddrreq
	(*Sgetwatchaddrresp)(nil), // 15: config.sgetwatchaddrresp
}
var file_api_sconfig_proto_depIdxs = []int32{
	0,  // 0: config.sconfig.sinfo:input_type -> config.sinforeq
	2,  // 1: config.sconfig.sset:input_type -> config.ssetreq
	4,  // 2: config.sconfig.srollback:input_type -> config.srollbackreq
	6,  // 3: config.sconfig.sget:input_type -> config.sgetreq
	8,  // 4: config.sconfig.sgroups:input_type -> config.sgroupsreq
	10, // 5: config.sconfig.sapps:input_type -> config.sappsreq
	12, // 6: config.sconfig.ssetwatchaddr:input_type -> config.ssetwatchaddrreq
	14, // 7: config.sconfig.sgetwatchaddr:input_type -> config.sgetwatchaddrreq
	1,  // 8: config.sconfig.sinfo:output_type -> config.sinforesp
	3,  // 9: config.sconfig.sset:output_type -> config.ssetresp
	5,  // 10: config.sconfig.srollback:output_type -> config.srollbackresp
	7,  // 11: config.sconfig.sget:output_type -> config.sgetresp
	9,  // 12: config.sconfig.sgroups:output_type -> config.sgroupsresp
	11, // 13: config.sconfig.sapps:output_type -> config.sappsresp
	13, // 14: config.sconfig.ssetwatchaddr:output_type -> config.ssetwatchaddrresp
	15, // 15: config.sconfig.sgetwatchaddr:output_type -> config.sgetwatchaddrresp
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_sconfig_proto_init() }
func file_api_sconfig_proto_init() {
	if File_api_sconfig_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_sconfig_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sinforeq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sconfig_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sinforesp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sconfig_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ssetreq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sconfig_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ssetresp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sconfig_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Srollbackreq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sconfig_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Srollbackresp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sconfig_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sgetreq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sconfig_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sgetresp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sconfig_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sgroupsreq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sconfig_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sgroupsresp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sconfig_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sappsreq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sconfig_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sappsresp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sconfig_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ssetwatchaddrreq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sconfig_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ssetwatchaddrresp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sconfig_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sgetwatchaddrreq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sconfig_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sgetwatchaddrresp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_sconfig_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_sconfig_proto_goTypes,
		DependencyIndexes: file_api_sconfig_proto_depIdxs,
		MessageInfos:      file_api_sconfig_proto_msgTypes,
	}.Build()
	File_api_sconfig_proto = out.File
	file_api_sconfig_proto_rawDesc = nil
	file_api_sconfig_proto_goTypes = nil
	file_api_sconfig_proto_depIdxs = nil
}
