// Code generated by protoc-gen-go-web. DO NOT EDIT.
// version:
// 	protoc-gen-web v0.0.1
// 	protoc         v3.17.3
// source: api/status_config.proto

package api

import (
	context "context"
	bufpool "github.com/chenjie199234/Corelib/bufpool"
	log "github.com/chenjie199234/Corelib/log"
	common "github.com/chenjie199234/Corelib/util/common"
	error1 "github.com/chenjie199234/Corelib/util/error"
	metadata "github.com/chenjie199234/Corelib/util/metadata"
	web "github.com/chenjie199234/Corelib/web"
	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	io "io"
	http "net/http"
	strings "strings"
)

var _StatusWebCheckers map[string]func(req interface{}) string

func init() {
	_StatusWebCheckers = make(map[string]func(req interface{}) string, 1)
	_StatusWebCheckers["\"\\\"config/api\\\"\".Pingreq"] = func(r interface{}) string {
		req := r.(*Pingreq)
		if req.Timestamp <= 0 {
			return "field: timestamp in object: pingreq check value int gt failed"
		}
		return ""
	}
}

var _WebPathStatusPing = "/config.status/ping"

type StatusWebClient interface {
	//ping check server's health
	Ping(context.Context, *Pingreq, http.Header) (*Pingresp, error)
}

type statusWebClient struct {
	cc *web.WebClient
}

func NewStatusWebClient(c *web.ClientConfig, selfgroup, selfname, peergroup, peername string) (StatusWebClient, error) {
	cc, e := web.NewWebClient(c, selfgroup, selfname, peergroup, peername)
	if e != nil {
		return nil, e
	}
	return &statusWebClient{cc: cc}, nil
}

func (c *statusWebClient) Ping(ctx context.Context, req *Pingreq, header http.Header) (*Pingresp, error) {
	if req == nil {
		return nil, error1.ErrReq
	}
	if s := _StatusWebCheckers["\"\\\"config/api\\\"\".Pingreq"](req); s != "" {
		log.Error("[/config.status/ping]", s)
		return nil, error1.ErrReq
	}
	if header == nil {
		header = make(http.Header)
	}
	header.Set("Content-Type", "application/x-www-form-urlencoded")
	header.Set("Accept", "application/x-protobuf")
	query := bufpool.GetBuffer()
	defer bufpool.PutBuffer(query)
	query.Append("?")
	if req.Timestamp != 0 {
		query.Append("timestamp=")
		query.Append(req.Timestamp)
		query.Append("&")
	}
	r, e := c.cc.Get(ctx, 200000000, _WebPathStatusPing+query.String(), header, metadata.GetAllMetadata(ctx))
	if e != nil {
		return nil, error1.StdErrorToError(e)
	}
	defer r.Body.Close()
	data, e := io.ReadAll(r.Body)
	if e != nil {
		return nil, error1.StdErrorToError(e)
	}
	if r.StatusCode/100 == 4 || r.StatusCode/100 == 5 {
		return nil, error1.ErrorstrToError(common.Byte2str(data))
	}
	resp := new(Pingresp)
	if len(data) == 0 {
		return resp, nil
	}
	if e := proto.Unmarshal(data, resp); e != nil {
		return nil, error1.ErrResp
	}
	return resp, nil
}

type StatusWebServer interface {
	//ping check server's health
	Ping(context.Context, *Pingreq) (*Pingresp, error)
}

func _Status_Ping_WebHandler(handler func(context.Context, *Pingreq) (*Pingresp, error)) web.OutsideHandler {
	return func(ctx *web.Context) {
		req := new(Pingreq)
		if strings.HasPrefix(ctx.GetContentType(), "application/json") {
			data, e := ctx.GetBody()
			if e != nil {
				ctx.AbortString(http.StatusBadRequest, e.Error())
				return
			}
			if len(data) > 0 {
				e := protojson.UnmarshalOptions{DiscardUnknown: true}.Unmarshal(data, req)
				if e != nil {
					ctx.AbortString(http.StatusBadRequest, error1.ErrReq.String())
					return
				}
			}
		} else if strings.HasPrefix(ctx.GetContentType(), "application/x-protobuf") {
			data, e := ctx.GetBody()
			if e != nil {
				ctx.AbortString(http.StatusBadRequest, e.Error())
				return
			}
			if len(data) > 0 {
				if e := proto.Unmarshal(data, req); e != nil {
					ctx.AbortString(http.StatusBadRequest, error1.ErrReq.String())
					return
				}
			}
		} else {
			if e := ctx.ParseForm(); e != nil {
				ctx.AbortString(http.StatusBadRequest, error1.ErrReq.String())
				return
			}
			data := bufpool.GetBuffer()
			defer bufpool.PutBuffer(data)
			data.Append("{")
			data.Append("\"timestamp\":")
			if form := ctx.GetForm("timestamp"); len(form) == 0 {
				data.Append("0")
			} else {
				data.Append(form)
			}
			data.Append("}")
			if data.Len() > 2 {
				e := protojson.UnmarshalOptions{DiscardUnknown: true}.Unmarshal(data.Bytes(), req)
				if e != nil {
					ctx.AbortString(http.StatusBadRequest, error1.ErrReq.String())
					return
				}
			}
		}
		if s := _StatusWebCheckers["\"\\\"config/api\\\"\".Pingreq"](req); s != "" {
			log.Error("[/config.status/ping]", s)
			ctx.AbortString(http.StatusBadRequest, error1.ErrReq.String())
			return
		}
		resp, e := handler(ctx, req)
		if e != nil {
			if error1.Equal(e, error1.ErrReq) {
				ctx.AbortString(http.StatusBadRequest, e.Error())
			} else {
				ctx.AbortString(http.StatusInternalServerError, e.Error())
			}
			return
		}
		if resp == nil {
			resp = new(Pingresp)
		}
		if strings.HasPrefix(ctx.GetAcceptType(), "application/x-protobuf") {
			respd, _ := proto.Marshal(resp)
			ctx.SetHeader("Content-Type", "application/x-protobuf")
			ctx.Write(http.StatusOK, respd)
		} else {
			respd, _ := protojson.MarshalOptions{UseProtoNames: true, UseEnumNumbers: true, EmitUnpopulated: true}.Marshal(resp)
			ctx.SetHeader("Content-Type", "application/json")
			ctx.Write(http.StatusOK, respd)
		}
	}
}
func RegisterStatusWebServer(engine *web.WebServer, svc StatusWebServer, allmids map[string]web.OutsideHandler) error {
	//avoid lint
	_ = allmids
	if e := engine.Get(_WebPathStatusPing, 200000000, _Status_Ping_WebHandler(svc.Ping)); e != nil {
		return e
	}
	return nil
}
